name: Build PyQt Client

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build-client:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-client.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-client.txt pyinstaller

      - name: Build executable
        shell: pwsh
        run: |
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          if (Test-Path build) { Remove-Item -Recurse -Force build }
          pyinstaller --noconfirm --onefile --name StratzScraperClient stratz_scraper/client/__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: StratzScraperClient-windows
          path: dist/StratzScraperClient.exe
